/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Cartoon Video Generator API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
export interface ApiError {
    error: string;
}
export interface DeleteResult {
    success: boolean;
}
export interface ImageGenInput {
    /** Cartoon image description */
    prompt: string;
    /**
       * Art style (anime, cartoon, ghibli, etc.)
       * @nullable
       */
    style?: string | null;
}
export interface ImageGenResult {
    /** Base64 data URL or hosted URL of the generated image */
    imageUrl: string;
    prompt: string;
}
export interface SpeechGenInput {
    /** Hindi text to convert to speech */
    text: string;
    /**
       * Language code (default hi)
       * @nullable
       */
    language?: string | null;
}
export interface SpeechGenResult {
    /** Base64-encoded audio data */
    audioBase64: string;
    mimeType: string;
}
export interface Scene {
    id: string;
    order: number;
    prompt: string;
    subtitle: string;
    /** @nullable */
    imageUrl?: string | null;
    /** @nullable */
    audioBase64?: string | null;
    /**
       * Duration in seconds
       * @nullable
       */
    duration?: number | null;
}
export interface VideoCompileInput {
    projectId: string;
    scenes: Scene[];
}
export interface VideoCompileResult {
    /** URL to download the compiled MP4 */
    videoUrl: string;
    projectId: string;
}
export interface Project {
    id: string;
    title: string;
    /** @nullable */
    description?: string | null;
    createdAt: string;
    /** @nullable */
    updatedAt?: string | null;
    /** draft | generating | ready | exported */
    status: string;
    scenes: Scene[];
    /** @nullable */
    videoUrl?: string | null;
    /** @nullable */
    thumbnailUrl?: string | null;
}
export interface ProjectInput {
    title: string;
    /** @nullable */
    description?: string | null;
    scenes?: Scene[];
}
export interface ProjectUpdate {
    /** @nullable */
    title?: string | null;
    /** @nullable */
    description?: string | null;
    /** @nullable */
    status?: string | null;
    scenes?: Scene[];
    /** @nullable */
    videoUrl?: string | null;
    /** @nullable */
    thumbnailUrl?: string | null;
}
//# sourceMappingURL=api.schemas.d.ts.map