/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Cartoon Video Generator API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Generate cartoon image from prompt via Hugging Face
 */
export const GenerateImageBody = zod.object({
  "prompt": zod.string().describe('Cartoon image description'),
  "style": zod.string().nullish().describe('Art style (anime, cartoon, ghibli, etc.)')
})

export const GenerateImageResponse = zod.object({
  "imageUrl": zod.string().describe('Base64 data URL or hosted URL of the generated image'),
  "prompt": zod.string()
})


/**
 * @summary Generate Hindi speech audio from text
 */
export const GenerateSpeechBody = zod.object({
  "text": zod.string().describe('Hindi text to convert to speech'),
  "language": zod.string().nullish().describe('Language code (default hi)')
})

export const GenerateSpeechResponse = zod.object({
  "audioBase64": zod.string().describe('Base64-encoded audio data'),
  "mimeType": zod.string()
})


/**
 * @summary Compile scenes into an MP4 video using FFmpeg
 */
export const CompileVideoBody = zod.object({
  "projectId": zod.string(),
  "scenes": zod.array(zod.object({
  "id": zod.string(),
  "order": zod.number(),
  "prompt": zod.string(),
  "subtitle": zod.string(),
  "imageUrl": zod.string().nullish(),
  "audioBase64": zod.string().nullish(),
  "duration": zod.number().nullish().describe('Duration in seconds')
}))
})

export const CompileVideoResponse = zod.object({
  "videoUrl": zod.string().describe('URL to download the compiled MP4'),
  "projectId": zod.string()
})


/**
 * @summary List all projects
 */
export const ListProjectsResponseItem = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date().nullish(),
  "status": zod.string().describe('draft | generating | ready | exported'),
  "scenes": zod.array(zod.object({
  "id": zod.string(),
  "order": zod.number(),
  "prompt": zod.string(),
  "subtitle": zod.string(),
  "imageUrl": zod.string().nullish(),
  "audioBase64": zod.string().nullish(),
  "duration": zod.number().nullish().describe('Duration in seconds')
})),
  "videoUrl": zod.string().nullish(),
  "thumbnailUrl": zod.string().nullish()
})
export const ListProjectsResponse = zod.array(ListProjectsResponseItem)


/**
 * @summary Create a new project
 */
export const CreateProjectBody = zod.object({
  "title": zod.string(),
  "description": zod.string().nullish(),
  "scenes": zod.array(zod.object({
  "id": zod.string(),
  "order": zod.number(),
  "prompt": zod.string(),
  "subtitle": zod.string(),
  "imageUrl": zod.string().nullish(),
  "audioBase64": zod.string().nullish(),
  "duration": zod.number().nullish().describe('Duration in seconds')
})).optional()
})


/**
 * @summary Get a project by ID
 */
export const GetProjectParams = zod.object({
  "id": zod.coerce.string()
})

export const GetProjectResponse = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date().nullish(),
  "status": zod.string().describe('draft | generating | ready | exported'),
  "scenes": zod.array(zod.object({
  "id": zod.string(),
  "order": zod.number(),
  "prompt": zod.string(),
  "subtitle": zod.string(),
  "imageUrl": zod.string().nullish(),
  "audioBase64": zod.string().nullish(),
  "duration": zod.number().nullish().describe('Duration in seconds')
})),
  "videoUrl": zod.string().nullish(),
  "thumbnailUrl": zod.string().nullish()
})


/**
 * @summary Update a project
 */
export const UpdateProjectParams = zod.object({
  "id": zod.coerce.string()
})

export const UpdateProjectBody = zod.object({
  "title": zod.string().nullish(),
  "description": zod.string().nullish(),
  "status": zod.string().nullish(),
  "scenes": zod.array(zod.object({
  "id": zod.string(),
  "order": zod.number(),
  "prompt": zod.string(),
  "subtitle": zod.string(),
  "imageUrl": zod.string().nullish(),
  "audioBase64": zod.string().nullish(),
  "duration": zod.number().nullish().describe('Duration in seconds')
})).optional(),
  "videoUrl": zod.string().nullish(),
  "thumbnailUrl": zod.string().nullish()
})

export const UpdateProjectResponse = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date().nullish(),
  "status": zod.string().describe('draft | generating | ready | exported'),
  "scenes": zod.array(zod.object({
  "id": zod.string(),
  "order": zod.number(),
  "prompt": zod.string(),
  "subtitle": zod.string(),
  "imageUrl": zod.string().nullish(),
  "audioBase64": zod.string().nullish(),
  "duration": zod.number().nullish().describe('Duration in seconds')
})),
  "videoUrl": zod.string().nullish(),
  "thumbnailUrl": zod.string().nullish()
})


/**
 * @summary Delete a project
 */
export const DeleteProjectParams = zod.object({
  "id": zod.coerce.string()
})

export const DeleteProjectResponse = zod.object({
  "success": zod.boolean()
})


