/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Cartoon Video Generator API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Generate cartoon image from prompt via Hugging Face
 */
export declare const GenerateImageBody: zod.ZodObject<{
    prompt: zod.ZodString;
    style: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    prompt: string;
    style?: string | null | undefined;
}, {
    prompt: string;
    style?: string | null | undefined;
}>;
export declare const GenerateImageResponse: zod.ZodObject<{
    imageUrl: zod.ZodString;
    prompt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    prompt: string;
    imageUrl: string;
}, {
    prompt: string;
    imageUrl: string;
}>;
/**
 * @summary Generate Hindi speech audio from text
 */
export declare const GenerateSpeechBody: zod.ZodObject<{
    text: zod.ZodString;
    language: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    text: string;
    language?: string | null | undefined;
}, {
    text: string;
    language?: string | null | undefined;
}>;
export declare const GenerateSpeechResponse: zod.ZodObject<{
    audioBase64: zod.ZodString;
    mimeType: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    audioBase64: string;
    mimeType: string;
}, {
    audioBase64: string;
    mimeType: string;
}>;
/**
 * @summary Compile scenes into an MP4 video using FFmpeg
 */
export declare const CompileVideoBody: zod.ZodObject<{
    projectId: zod.ZodString;
    scenes: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        order: zod.ZodNumber;
        prompt: zod.ZodString;
        subtitle: zod.ZodString;
        imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        audioBase64: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        duration: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    }, "strip", zod.ZodTypeAny, {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }, {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    projectId: string;
    scenes: {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }[];
}, {
    projectId: string;
    scenes: {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }[];
}>;
export declare const CompileVideoResponse: zod.ZodObject<{
    videoUrl: zod.ZodString;
    projectId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    projectId: string;
    videoUrl: string;
}, {
    projectId: string;
    videoUrl: string;
}>;
/**
 * @summary List all projects
 */
export declare const ListProjectsResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    status: zod.ZodString;
    scenes: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        order: zod.ZodNumber;
        prompt: zod.ZodString;
        subtitle: zod.ZodString;
        imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        audioBase64: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        duration: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    }, "strip", zod.ZodTypeAny, {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }, {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }>, "many">;
    videoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    thumbnailUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    scenes: {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }[];
    id: string;
    title: string;
    createdAt: Date;
    videoUrl?: string | null | undefined;
    description?: string | null | undefined;
    updatedAt?: Date | null | undefined;
    thumbnailUrl?: string | null | undefined;
}, {
    status: string;
    scenes: {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }[];
    id: string;
    title: string;
    createdAt: Date;
    videoUrl?: string | null | undefined;
    description?: string | null | undefined;
    updatedAt?: Date | null | undefined;
    thumbnailUrl?: string | null | undefined;
}>;
export declare const ListProjectsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    status: zod.ZodString;
    scenes: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        order: zod.ZodNumber;
        prompt: zod.ZodString;
        subtitle: zod.ZodString;
        imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        audioBase64: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        duration: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    }, "strip", zod.ZodTypeAny, {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }, {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }>, "many">;
    videoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    thumbnailUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    scenes: {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }[];
    id: string;
    title: string;
    createdAt: Date;
    videoUrl?: string | null | undefined;
    description?: string | null | undefined;
    updatedAt?: Date | null | undefined;
    thumbnailUrl?: string | null | undefined;
}, {
    status: string;
    scenes: {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }[];
    id: string;
    title: string;
    createdAt: Date;
    videoUrl?: string | null | undefined;
    description?: string | null | undefined;
    updatedAt?: Date | null | undefined;
    thumbnailUrl?: string | null | undefined;
}>, "many">;
/**
 * @summary Create a new project
 */
export declare const CreateProjectBody: zod.ZodObject<{
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    scenes: zod.ZodOptional<zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        order: zod.ZodNumber;
        prompt: zod.ZodString;
        subtitle: zod.ZodString;
        imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        audioBase64: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        duration: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    }, "strip", zod.ZodTypeAny, {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }, {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }>, "many">>;
}, "strip", zod.ZodTypeAny, {
    title: string;
    scenes?: {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }[] | undefined;
    description?: string | null | undefined;
}, {
    title: string;
    scenes?: {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }[] | undefined;
    description?: string | null | undefined;
}>;
/**
 * @summary Get a project by ID
 */
export declare const GetProjectParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const GetProjectResponse: zod.ZodObject<{
    id: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    status: zod.ZodString;
    scenes: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        order: zod.ZodNumber;
        prompt: zod.ZodString;
        subtitle: zod.ZodString;
        imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        audioBase64: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        duration: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    }, "strip", zod.ZodTypeAny, {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }, {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }>, "many">;
    videoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    thumbnailUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    scenes: {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }[];
    id: string;
    title: string;
    createdAt: Date;
    videoUrl?: string | null | undefined;
    description?: string | null | undefined;
    updatedAt?: Date | null | undefined;
    thumbnailUrl?: string | null | undefined;
}, {
    status: string;
    scenes: {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }[];
    id: string;
    title: string;
    createdAt: Date;
    videoUrl?: string | null | undefined;
    description?: string | null | undefined;
    updatedAt?: Date | null | undefined;
    thumbnailUrl?: string | null | undefined;
}>;
/**
 * @summary Update a project
 */
export declare const UpdateProjectParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const UpdateProjectBody: zod.ZodObject<{
    title: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    scenes: zod.ZodOptional<zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        order: zod.ZodNumber;
        prompt: zod.ZodString;
        subtitle: zod.ZodString;
        imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        audioBase64: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        duration: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    }, "strip", zod.ZodTypeAny, {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }, {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }>, "many">>;
    videoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    thumbnailUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status?: string | null | undefined;
    scenes?: {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }[] | undefined;
    videoUrl?: string | null | undefined;
    title?: string | null | undefined;
    description?: string | null | undefined;
    thumbnailUrl?: string | null | undefined;
}, {
    status?: string | null | undefined;
    scenes?: {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }[] | undefined;
    videoUrl?: string | null | undefined;
    title?: string | null | undefined;
    description?: string | null | undefined;
    thumbnailUrl?: string | null | undefined;
}>;
export declare const UpdateProjectResponse: zod.ZodObject<{
    id: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    status: zod.ZodString;
    scenes: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        order: zod.ZodNumber;
        prompt: zod.ZodString;
        subtitle: zod.ZodString;
        imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        audioBase64: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        duration: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    }, "strip", zod.ZodTypeAny, {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }, {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }>, "many">;
    videoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    thumbnailUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    scenes: {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }[];
    id: string;
    title: string;
    createdAt: Date;
    videoUrl?: string | null | undefined;
    description?: string | null | undefined;
    updatedAt?: Date | null | undefined;
    thumbnailUrl?: string | null | undefined;
}, {
    status: string;
    scenes: {
        prompt: string;
        id: string;
        order: number;
        subtitle: string;
        imageUrl?: string | null | undefined;
        audioBase64?: string | null | undefined;
        duration?: number | null | undefined;
    }[];
    id: string;
    title: string;
    createdAt: Date;
    videoUrl?: string | null | undefined;
    description?: string | null | undefined;
    updatedAt?: Date | null | undefined;
    thumbnailUrl?: string | null | undefined;
}>;
/**
 * @summary Delete a project
 */
export declare const DeleteProjectParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const DeleteProjectResponse: zod.ZodObject<{
    success: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    success: boolean;
}, {
    success: boolean;
}>;
//# sourceMappingURL=api.d.ts.map