/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Cartoon Video Generator API
 * OpenAPI spec version: 0.1.0
 */
export interface ImageGenResult {
    /** Base64 data URL or hosted URL of the generated image */
    imageUrl: string;
    prompt: string;
}
//# sourceMappingURL=imageGenResult.d.ts.map