/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Cartoon Video Generator API
 * OpenAPI spec version: 0.1.0
 */
export interface ImageGenInput {
    /** Cartoon image description */
    prompt: string;
    /**
       * Art style (anime, cartoon, ghibli, etc.)
       * @nullable
       */
    style?: string | null;
}
//# sourceMappingURL=imageGenInput.d.ts.map