/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Cartoon Video Generator API
 * OpenAPI spec version: 0.1.0
 */
import type { Scene } from './scene';

export interface ProjectUpdate {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  status?: string | null;
  scenes?: Scene[];
  /** @nullable */
  videoUrl?: string | null;
  /** @nullable */
  thumbnailUrl?: string | null;
}
