/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Cartoon Video Generator API
 * OpenAPI spec version: 0.1.0
 */
import type { Scene } from './scene';

export interface Project {
  id: string;
  title: string;
  /** @nullable */
  description?: string | null;
  createdAt: Date;
  /** @nullable */
  updatedAt?: Date | null;
  /** draft | generating | ready | exported */
  status: string;
  scenes: Scene[];
  /** @nullable */
  videoUrl?: string | null;
  /** @nullable */
  thumbnailUrl?: string | null;
}
