/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Cartoon Video Generator API
 * OpenAPI spec version: 0.1.0
 */

export interface Scene {
  id: string;
  order: number;
  prompt: string;
  subtitle: string;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  audioBase64?: string | null;
  /**
     * Duration in seconds
     * @nullable
     */
  duration?: number | null;
}
