/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Cartoon Video Generator API
 * OpenAPI spec version: 0.1.0
 */

export interface SpeechGenInput {
  /** Hindi text to convert to speech */
  text: string;
  /**
     * Language code (default hi)
     * @nullable
     */
  language?: string | null;
}
