/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Cartoon Video Generator API
 * OpenAPI spec version: 0.1.0
 */
export interface SpeechGenResult {
    /** Base64-encoded audio data */
    audioBase64: string;
    mimeType: string;
}
//# sourceMappingURL=speechGenResult.d.ts.map