/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Cartoon Video Generator API
 * OpenAPI spec version: 0.1.0
 */
export interface VideoCompileResult {
    /** URL to download the compiled MP4 */
    videoUrl: string;
    projectId: string;
}
//# sourceMappingURL=videoCompileResult.d.ts.map