/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Cartoon Video Generator API
 * OpenAPI spec version: 0.1.0
 */
import type { Scene } from './scene';

export interface VideoCompileInput {
  projectId: string;
  scenes: Scene[];
}
